alias cls="cd && clear"
alias dir="dir --color=auto"
alias grep="grep --color=auto"
alias ls="ls --color=auto"
alias ll="ls -la --color=auto"
alias la="ls -a --color=auto"
alias l="ls -l --color=auto"
